"""Static abbreviation swaps for common English and tech phrases (~300).

Maps lowercase multi-word / long forms to shorter abbreviations that typically
cost fewer BPE tokens. Applied whole-phrase, case-preserving where practical.
"""

from __future__ import annotations

# ~300 curated entries. Prefer high-frequency chat/tech forms and multi-word
# phrases that clearly shorten. Apply longest keys first at runtime.
ABBREVIATIONS: dict[str, str] = {
    "continuous integration and continuous delivery": "CI/CD",
    "continuous integration continuous delivery": "CI/CD",
    "continuous integration/continuous delivery": "CI/CD",
    "integrated development environment": "IDE",
    "application programming interface": "API",
    "application programming interfaces": "APIs",
    "retrieval augmented generation": "RAG",
    "retrieval-augmented generation": "RAG",
    "natural language processing": "NLP",
    "relational database service": "RDS",
    "javascript object notation": "JSON",
    "graphical user interface": "GUI",
    "artificial intelligence": "AI",
    "service level agreement": "SLA",
    "service level objective": "SLO",
    "service level indicator": "SLI",
    "continuous integration": "CI",
    "minimum viable product": "MVP",
    "large language model": "LLM",
    "large language models": "LLMs",
    "database as a service": "DBaaS",
    "development environment": "dev env",
    "as soon as possible": "ASAP",
    "institute of electrical and electronics engineers": "IEEE",
    "machine learning": "ML",
    "production environment": "prod env",
    "due to the fact that": "because",
    "proof of concept": "PoC",
    "user experience": "UX",
    "international organization for standardization": "ISO",
    "user interface": "UI",
    "staging environment": "stg env",
    "national institute of standards and technology": "NIST",
    "merge request": "MR",
    "merge requests": "MRs",
    "that is to say": "i.e.",
    "pull request": "PR",
    "pull requests": "PRs",
    "in order to": "to",
    "for example": "e.g.",
    "by the way": "BTW",
    "that is": "i.e.",
    "common vulnerabilities and exposures": "CVE",
    "personally identifiable information": "PII",
    "open web application security project": "OWASP",
    "dynamic application security testing": "DAST",
    "static application security testing": "SAST",
    "documentation": "docs",
    "general data protection regulation": "GDPR",
    "environment": "env",
    "environments": "envs",
    "javascript": "JS",
    "typescript": "TS",
    "customer relationship management": "CRM",
    "hypertext transfer protocol secure": "HTTPS",
    "configuration": "config",
    "configurations": "configs",
    "kubernetes": "k8s",
    "repository": "repo",
    "database": "DB",
    "databases": "DBs",
    "representational state transfer": "REST",
    "identity and access management": "IAM",
    "optical character recognition": "OCR",
    "software composition analysis": "SCA",
    "enterprise resource planning": "ERP",
    "distributed denial of service": "DDoS",
    "site reliability engineering": "SRE",
    "universally unique identifier": "UUID",
    "free and open source software": "FOSS",
    "memorandum of understanding": "MOU",
    "object oriented programming": "OOP",
    "object-oriented programming": "OOP",
    "behavior driven development": "BDD",
    "behavior-driven development": "BDD",
    "create, read, update, delete": "CRUD",
    "multi factor authentication": "MFA",
    "multi-factor authentication": "MFA",
    "principle of least privilege": "PoLP",
    "progressive web application": "PWA",
    "uniform resource identifier": "URI",
    "frequently asked questions": "FAQ",
    "infrastructure as a service": "IaaS",
    "extensible markup language": "XML",
    "hypertext transfer protocol": "HTTP",
    "security operations center": "SOC",
    "custom resource definition": "CRD",
    "frequently asked question": "FAQ",
    "key performance indicator": "KPI",
    "key performance indicators": "KPIs",
    "content management system": "CMS",
    "monthly recurring revenue": "MRR",
    "customer acquisition cost": "CAC",
    "chief information officer": "CIO",
    "estimated time of arrival": "ETA",
    "structured query language": "SQL",
    "two factor authentication": "2FA",
    "two-factor authentication": "2FA",
    "cross site request forgery": "CSRF",
    "cross-site request forgery": "CSRF",
    "site reliability engineer": "SRE",
    "mean time between failures": "MTBF",
    "software bill of materials": "SBOM",
    "object relational mapping": "ORM",
    "object-relational mapping": "ORM",
    "globally unique identifier": "GUID",
    "horizontal pod autoscaler": "HPA",
    "world health organization": "WHO",
    "research and development": "R&D",
    "annual recurring revenue": "ARR",
    "non disclosure agreement": "NDA",
    "non-disclosure agreement": "NDA",
    "chief technology officer": "CTO",
    "software development kit": "SDK",
    "software development kits": "SDKs",
    "hypertext markup language": "HTML",
    "create read update delete": "CRUD",
    "extract, transform, load": "ETL",
    "graphics processing unit": "GPU",
    "transport layer security": "TLS",
    "content delivery network": "CDN",
    "role based access control": "RBAC",
    "role-based access control": "RBAC",
    "recovery point objective": "RPO",
    "business continuity plan": "BCP",
    "uniform resource locator": "URL",
    "on account of the fact that": "because",
    "service-level agreement": "SLA",
    "average revenue per user": "ARPU",
    "total cost of ownership": "TCO",
    "chief executive officer": "CEO",
    "chief financial officer": "CFO",
    "chief operating officer": "COO",
    "individual contributor": "IC",
    "user acceptance testing": "UAT",
    "test driven development": "TDD",
    "test-driven development": "TDD",
    "central processing unit": "CPU",
    "virtual private network": "VPN",
    "recovery time objective": "RTO",
    "single page application": "SPA",
    "single-page application": "SPA",
    "functional programming": "FP",
    "common table expression": "CTE",
    "simple storage service": "S3",
    "information technology": "IT",
    "research & development": "R&D",
    "infrastructure as code": "IaC",
    "continuous deployment": "CD",
    "command line interface": "CLI",
    "cascading style sheets": "CSS",
    "do not repeat yourself": "DRY",
    "extract transform load": "ETL",
    "separation of concerns": "SoC",
    "static site generation": "SSG",
    "general public license": "GPL",
    "at this point in time": "now",
    "in light of the fact that": "because",
    "anti money laundering": "AML",
    "anti-money laundering": "AML",
    "chief product officer": "CPO",
    "subject matter expert": "SME",
    "remote procedure call": "RPC",
    "don't repeat yourself": "DRY",
    "model view controller": "MVC",
    "virtual private cloud": "VPC",
    "google cloud platform": "GCP",
    "server side rendering": "SSR",
    "server-side rendering": "SSR",
    "client side rendering": "CSR",
    "client-side rendering": "CSR",
    "dependency injection": "DI",
    "elastic compute cloud": "EC2",
    "for your information": "FYI",
    "return on investment": "ROI",
    "quarter over quarter": "QoQ",
    "request for comments": "RFC",
    "request for proposal": "RFP",
    "business to business": "B2B",
    "business to consumer": "B2C",
    "software as a service": "SaaS",
    "platform as a service": "PaaS",
    "function as a service": "FaaS",
    "engineering manager": "EM",
    "acceptance criteria": "AC",
    "continuous delivery": "CD",
    "domain driven design": "DDD",
    "domain-driven design": "DDD",
    "random access memory": "RAM",
    "secure sockets layer": "SSL",
    "cross site scripting": "XSS",
    "cross-site scripting": "XSS",
    "mean time to recovery": "MTTR",
    "software engineering": "SWE",
    "inversion of control": "IoC",
    "abstract syntax tree": "AST",
    "data transfer object": "DTO",
    "open source software": "OSS",
    "node package manager": "npm",
    "in my humble opinion": "IMHO",
    "for the purposes of": "for",
    "have the ability to": "can",
    "at the present time": "now",
    "terms and conditions": "T&Cs",
    "backend as a service": "BaaS",
    "amazon web services": "AWS",
    "root cause analysis": "RCA",
    "root-cause analysis": "RCA",
    "progressive web app": "PWA",
    "garbage collection": "GC",
    "python package index": "PyPI",
    "in the event that": "if",
    "for the purpose of": "for",
    "with the exception of": "except",
    "has the ability to": "can",
    "take into consideration": "consider",
    "owing to the fact that": "because",
    "quality assurance": "QA",
    "net promoter score": "NPS",
    "stock keeping unit": "SKU",
    "stock keeping units": "SKUs",
    "know your customer": "KYC",
    "definition of done": "DoD",
    "internet of things": "IoT",
    "domain name system": "DNS",
    "high availability": "HA",
    "disaster recovery": "DR",
    "incident response": "IR",
    "data access object": "DAO",
    "availability zone": "AZ",
    "auto scaling group": "ASG",
    "close of business": "COB",
    "a small number of": "few",
    "in the near future": "soon",
    "provide assistance": "help",
    "it is possible to": "can",
    "it is necessary to": "must",
    "there is a need to": "must",
    "statement of work": "SOW",
    "bill of materials": "BOM",
    "operating system": "OS",
    "solid state drive": "SSD",
    "denial of service": "DoS",
    "application security": "AppSec",
    "software engineer": "SWE",
    "creative commons": "CC",
    "to be determined": "TBD",
    "original poster": "OP",
    "in the event of": "if",
    "a large number of": "many",
    "month over month": "MoM",
    "terms of service": "ToS",
    "human resources": "HR",
    "quality control": "QC",
    "project manager": "PM",
    "product manager": "PM",
    "work in progress": "WIP",
    "computer vision": "CV",
    "virtual machine": "VM",
    "virtual machines": "VMs",
    "information security": "InfoSec",
    "with regard to": "re",
    "to be announced": "TBA",
    "vice president": "VP",
    "technical lead": "TL",
    "hard disk drive": "HDD",
    "united kingdom": "UK",
    "european union": "EU",
    "united nations": "UN",
    "not applicable": "N/A",
    "the majority of": "most",
    "on a daily basis": "daily",
    "on a weekly basis": "weekly",
    "on a monthly basis": "monthly",
    "on a yearly basis": "yearly",
    "year over year": "YoY",
    "week over week": "WoW",
    "infrastructure-as-code": "IaC",
    "lifetime value": "LTV",
    "time to market": "TTM",
    "speech to text": "STT",
    "text to speech": "TTS",
    "single sign on": "SSO",
    "single sign-on": "SSO",
    "load balancer": "LB",
    "blue green deployment": "blue/green",
    "blue-green deployment": "blue/green",
    "canary deployment": "canary",
    "github actions": "GHA",
    "visual studio code": "VS Code",
    "united states": "US",
    "san francisco": "SF",
    "in regard to": "re",
    "in my opinion": "IMO",
    "i do not know": "IDK",
    "not available": "N/A",
    "point of view": "POV",
    "out of office": "OOO",
    "in a timely manner": "promptly",
    "on an annual basis": "annually",
}


def abbreviation_count() -> int:
    return len(ABBREVIATIONS)
